-- =============================================================================
-- 2.空域区块.sql
-- 表名称：public.bo_airspace_block
-- 表说明：空域区块信息表
-- 依赖说明：PostGIS 空间扩展。
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS postgis;

-- 删除空域区块父表。
-- CASCADE 会同时删除挂在父表下的所有分区表，例如：
--   public.bo_airspace_block_2026_09
--   public.bo_airspace_block_2026_10
--   public.bo_airspace_block_default
DROP TABLE IF EXISTS public.bo_airspace_block CASCADE;

CREATE TABLE public.bo_airspace_block (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outid varchar(255) NOT NULL,
    airspace_code varchar(255),
    airspace_name varchar(255),
    airspace_type varchar(255),
    airspace_area double precision,
    airspace_state varchar(255),
    min_height double precision,
    max_height double precision,
    use_date date NOT NULL,
    time_plan varchar(4000),
    status varchar(255),
    use_enabled boolean NOT NULL DEFAULT true,
    fence_type varchar(20),
    remark varchar(1000),
    create_time timestamp(6) without time zone NOT NULL,
    create_user varchar(32),
    update_time timestamp(6) without time zone NOT NULL,
    update_user varchar(32),
    del_flag boolean NOT NULL DEFAULT false,
    geom geometry(Geometry, 4326),
    CONSTRAINT pk_bo_airspace_block PRIMARY KEY (id, use_date)
) PARTITION BY RANGE (use_date);

-- 默认分区：当 use_date 没有匹配到已创建的日期分区时，数据会进入该分区。
-- 作用：防止忘记提前创建日期分区时插入失败；后续可再迁移到正式日期分区。
CREATE TABLE public.bo_airspace_block_default
    PARTITION OF public.bo_airspace_block
    DEFAULT;

COMMENT ON TABLE public.bo_airspace_block IS '空域区块信息表';

COMMENT ON COLUMN public.bo_airspace_block.id IS '主键';
COMMENT ON COLUMN public.bo_airspace_block.outid IS 'OutId';
COMMENT ON COLUMN public.bo_airspace_block.airspace_code IS '空域编号';
COMMENT ON COLUMN public.bo_airspace_block.airspace_name IS '空域名称';
COMMENT ON COLUMN public.bo_airspace_block.airspace_type IS '空域类型（B类、D类）';
COMMENT ON COLUMN public.bo_airspace_block.airspace_area IS '空域面积，单位：平方公里';
COMMENT ON COLUMN public.bo_airspace_block.airspace_state IS '空域状态（管制 监视）';
COMMENT ON COLUMN public.bo_airspace_block.min_height IS '生效最低高度，单位：米';
COMMENT ON COLUMN public.bo_airspace_block.max_height IS '生效最高高度，单位：米';
COMMENT ON COLUMN public.bo_airspace_block.use_date IS '使用日期，分区键';
COMMENT ON COLUMN public.bo_airspace_block.time_plan IS '时间计划，第三方原始多段时间数据';
COMMENT ON COLUMN public.bo_airspace_block.status IS '数据状态：1=可用，0=不可用';
COMMENT ON COLUMN public.bo_airspace_block.use_enabled IS '当前时间是否可用';
COMMENT ON COLUMN public.bo_airspace_block.fence_type IS '围栏类型：1=禁飞区，2=管控区，3=试飞区/适飞区';
COMMENT ON COLUMN public.bo_airspace_block.remark IS '备注';
COMMENT ON COLUMN public.bo_airspace_block.create_time IS '创建时间';
COMMENT ON COLUMN public.bo_airspace_block.create_user IS '创建者';
COMMENT ON COLUMN public.bo_airspace_block.update_time IS '更新时间';
COMMENT ON COLUMN public.bo_airspace_block.update_user IS '更新者';
COMMENT ON COLUMN public.bo_airspace_block.del_flag IS '是否删除：t删除；f未删除';
COMMENT ON COLUMN public.bo_airspace_block.geom IS '空域范围，WGS84坐标系';

CREATE INDEX idx_bo_airspace_block_geom
    ON public.bo_airspace_block
    USING gist (geom);

-- =============================================================================
-- 函数名称：gis_create_airspace_block_day_partitions
-- 函数功能：按日自动创建空域区块分区表
-- 函数描述：
--   1. 根据传入开始日期，从该日期开始连续创建日分区。
--   2. 分区表命名规则：bo_airspace_block_YYYY_MM_DD。
--   3. 函数可重复执行，已存在的日期分区不会重复创建。
--   4. 建议由定时任务或程序启动时提前创建未来日期分区。
-- 参数说明：
--   p_start_date  起始日期，默认当前日期。
--   p_days        连续创建天数，默认32天。
-- 使用示例：
--   SELECT public.gis_create_airspace_block_day_partitions(current_date, 32);
-- =============================================================================

-- =============================================================================
-- 删除函数
-- =============================================================================
SELECT gis_drop_function('gis_create_airspace_block_month_partitions');
SELECT gis_drop_function('gis_create_airspace_block_day_partitions');

-- =============================================================================
-- 函数介绍：gis_create_airspace_block_day_partitions
-- 主要作用：按日自动创建空域区块分区表。
-- 入参说明：起始日期、连续创建天数。
-- 返回说明：无返回值；函数执行完成后，缺失的日期分区会被自动创建。
-- =============================================================================
CREATE OR REPLACE FUNCTION public.gis_create_airspace_block_day_partitions(
    p_start_date date DEFAULT current_date,
    p_days integer DEFAULT 32
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_day_start date;
    v_day_end date;
    v_partition_name text;
    i integer;
BEGIN
    IF p_days IS NULL OR p_days <= 0 THEN
        RAISE EXCEPTION 'p_days must be greater than 0';
    END IF;

    FOR i IN 0..(p_days - 1) LOOP
        v_day_start := (p_start_date + i)::date;
        v_day_end := (v_day_start + 1)::date;
        v_partition_name := format('bo_airspace_block_%s', to_char(v_day_start, 'YYYY_MM_DD'));

        IF to_regclass(format('public.%I', v_partition_name)) IS NULL THEN
            EXECUTE format(
                'CREATE TABLE public.%I PARTITION OF public.bo_airspace_block FOR VALUES FROM (%L) TO (%L)',
                v_partition_name,
                v_day_start,
                v_day_end
            );
        END IF;
    END LOOP;
END;
$$;

COMMENT ON FUNCTION public.gis_create_airspace_block_day_partitions(date, integer)
IS '按日自动创建空域区块分区表';

-- =============================================================================
-- 调用示例
-- =============================================================================
-- 1. 从当前日期开始，自动创建未来32天分区。
-- SELECT public.gis_create_airspace_block_day_partitions(current_date, 32);
--
-- 2. 从指定日期开始，自动创建32天分区。
-- SELECT public.gis_create_airspace_block_day_partitions(DATE '2026-09-24', 32);
--
-- 3. 从2026年10月1日开始，自动创建7天分区。
-- SELECT public.gis_create_airspace_block_day_partitions(DATE '2026-10-01', 7);

-- 创建示例数据覆盖日期：2026-09-24 至 2026-10-25。
SELECT public.gis_create_airspace_block_day_partitions(DATE '2026-09-24', 32);

-- =============================================================================
-- 示例数据：2026-09-24 到 2026-10-25，聊城市区空域区块 1000 条。
-- 坐标说明：WGS84，经纬度范围位于聊城市区附近。
-- =============================================================================
INSERT INTO public.bo_airspace_block (
    outid,
    airspace_code,
    airspace_name,
    airspace_type,
    airspace_area,
    airspace_state,
    min_height,
    max_height,
    use_date,
    time_plan,
    status,
    use_enabled,
    fence_type,
    remark,
    create_time,
    create_user,
    update_time,
    update_user,
    del_flag,
    geom
)
WITH demo_data AS (
    SELECT
        gs AS seq,
        (DATE '2026-09-24' + ((gs - 1) % 32))::date AS plan_date,
        115.925 + (((gs - 1) % 40) * 0.0020) AS min_lon,
        36.410 + (((gs - 1) / 40) * 0.0018) AS min_lat,
        0.0012 + ((gs % 5) * 0.00015) AS lon_size,
        0.0010 + ((gs % 4) * 0.00015) AS lat_size
    FROM generate_series(1, 1000) AS gs
)
SELECT
    format('third-lc-%s', lpad(seq::text, 4, '0')) AS outid,
    format('LC-AS-%s', lpad(seq::text, 4, '0')) AS airspace_code,
    format('聊城市区空域区块%s', lpad(seq::text, 4, '0')) AS airspace_name,
    CASE WHEN seq % 2 = 0 THEN 'B类' ELSE 'D类' END AS airspace_type,
    round((0.018 + (seq % 7) * 0.006)::numeric, 3)::double precision AS airspace_area,
    CASE WHEN seq % 3 = 0 THEN '监视' ELSE '管制' END AS airspace_state,
    CASE WHEN seq % 4 = 0 THEN 30 ELSE 0 END::double precision AS min_height,
    CASE WHEN seq % 5 = 0 THEN 180 ELSE 120 END::double precision AS max_height,
    plan_date AS use_date,
    jsonb_build_array(
        jsonb_build_object(
            'startTime', to_char(plan_date, 'YYYY-MM-DD'),
            'endTime', to_char(plan_date, 'YYYY-MM-DD')
        ),
        jsonb_build_object(
            'startTime', to_char(plan_date, 'YYYY-MM-DD'),
            'endTime', to_char(plan_date, 'YYYY-MM-DD')
        )
    )::text AS time_plan,
    '1' AS status,
    true AS use_enabled,
    ((seq - 1) % 3 + 1)::text AS fence_type,
    '示例数据：聊城市区范围内批量生成空域区块' AS remark,
    now() AS create_time,
    'system' AS create_user,
    now() AS update_time,
    'system' AS update_user,
    false AS del_flag,
    ST_MakeEnvelope(min_lon, min_lat, min_lon + lon_size, min_lat + lat_size, 4326) AS geom
FROM demo_data;
