-- =============================================================================
-- 2.空域区块.sql
-- 表说明：
--   1. 空域区块：第三方同步过来的空域区块基础信息，一条区块只保存一份。
--   2. 用空计划：区块下的计划明细，一个区块可以对应多个计划。
-- 依赖说明：PostGIS 空间扩展。
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS postgis;

-- =============================================================================
-- 删除用空计划明细表
-- =============================================================================
DROP TABLE IF EXISTS public.bo_airspace_plan CASCADE;

-- =============================================================================
-- 删除空域区块主表
-- =============================================================================
DROP TABLE IF EXISTS public.bo_airspace_block CASCADE;

-- =============================================================================
-- 一、空域区块主表
-- =============================================================================
-- =============================================================================
-- 创建空域区块主表
-- =============================================================================
CREATE TABLE public.bo_airspace_block (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outid varchar(255) NOT NULL,
    unit_id varchar(64),
    unit_name varchar(255),
    airspace_code varchar(255),
    airspace_name varchar(255),
    airspace_type varchar(255),
    airspace_area double precision,
    airspace_state varchar(255),
    fence_type varchar(20),
    remark varchar(1000),
    sync_time timestamp(6) without time zone NOT NULL DEFAULT now(),
    create_time timestamp(6) without time zone NOT NULL DEFAULT now(),
    create_user varchar(32),
    update_time timestamp(6) without time zone NOT NULL DEFAULT now(),
    update_user varchar(32),
    del_flag boolean NOT NULL DEFAULT false,
    geom geometry(Geometry, 4326),
    CONSTRAINT pk_bo_airspace_block PRIMARY KEY (id),
    CONSTRAINT uk_bo_airspace_block_outid UNIQUE (outid)
);

COMMENT ON TABLE public.bo_airspace_block IS '空域区块主表，第三方同步过来的区块基础信息';

COMMENT ON COLUMN public.bo_airspace_block.id IS '主键';
COMMENT ON COLUMN public.bo_airspace_block.outid IS '第三方空域区块唯一标识';
COMMENT ON COLUMN public.bo_airspace_block.unit_id IS '所属单位ID';
COMMENT ON COLUMN public.bo_airspace_block.unit_name IS '所属单位名称';
COMMENT ON COLUMN public.bo_airspace_block.airspace_code IS '空域编号';
COMMENT ON COLUMN public.bo_airspace_block.airspace_name IS '空域名称';
COMMENT ON COLUMN public.bo_airspace_block.airspace_type IS '空域类型字典编码：管制空域、监视空域、报告空域';
COMMENT ON COLUMN public.bo_airspace_block.airspace_area IS '空域面积，单位：平方公里';
COMMENT ON COLUMN public.bo_airspace_block.airspace_state IS '默认状态字典编码：管控、报告、监视';
COMMENT ON COLUMN public.bo_airspace_block.fence_type IS '围栏类型：1=禁飞区，2=管控区，3=试飞区/适飞区';
COMMENT ON COLUMN public.bo_airspace_block.remark IS '备注';
COMMENT ON COLUMN public.bo_airspace_block.sync_time IS '第三方同步时间';
COMMENT ON COLUMN public.bo_airspace_block.create_time IS '创建时间';
COMMENT ON COLUMN public.bo_airspace_block.create_user IS '创建者';
COMMENT ON COLUMN public.bo_airspace_block.update_time IS '更新时间';
COMMENT ON COLUMN public.bo_airspace_block.update_user IS '更新者';
COMMENT ON COLUMN public.bo_airspace_block.del_flag IS '是否删除：t删除；f未删除';
COMMENT ON COLUMN public.bo_airspace_block.geom IS '空域范围，WGS84坐标系';

CREATE INDEX idx_bo_airspace_block_geom
    ON public.bo_airspace_block
    USING gist (geom);

CREATE INDEX idx_bo_airspace_block_unit
    ON public.bo_airspace_block (unit_id);

-- =============================================================================
-- 二、用空计划明细表
-- =============================================================================
-- =============================================================================
-- 创建用空计划明细表
-- =============================================================================
CREATE TABLE public.bo_airspace_plan (
    plan_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    block_id bigint NOT NULL,
    plan_outid varchar(255) NOT NULL,
    use_date date NOT NULL,
    time_plan varchar(4000),
    min_height double precision,
    max_height double precision,
    buffer_height double precision,
    plan_status varchar(255) NOT NULL DEFAULT '1',
    remark varchar(1000),
    create_time timestamp(6) without time zone NOT NULL DEFAULT now(),
    create_user varchar(32),
    update_time timestamp(6) without time zone NOT NULL DEFAULT now(),
    update_user varchar(32),
    del_flag boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_bo_airspace_plan PRIMARY KEY (plan_id, use_date),
    CONSTRAINT uk_bo_airspace_plan_outid_date UNIQUE (plan_outid, use_date),
    CONSTRAINT fk_bo_airspace_plan_block FOREIGN KEY (block_id)
        REFERENCES public.bo_airspace_block (id)
) PARTITION BY RANGE (use_date);

COMMENT ON TABLE public.bo_airspace_plan IS '用空计划明细表，一个空域区块可以对应多个用空计划';

COMMENT ON COLUMN public.bo_airspace_plan.plan_id IS '计划主键';
COMMENT ON COLUMN public.bo_airspace_plan.block_id IS '空域区块ID，关联bo_airspace_block.id';
COMMENT ON COLUMN public.bo_airspace_plan.plan_outid IS '第三方用空计划唯一标识';
COMMENT ON COLUMN public.bo_airspace_plan.use_date IS '使用日期，分区键';
COMMENT ON COLUMN public.bo_airspace_plan.time_plan IS '时间计划，仅保存时分秒，支持多段时间';
COMMENT ON COLUMN public.bo_airspace_plan.min_height IS '计划最低高度，单位：米';
COMMENT ON COLUMN public.bo_airspace_plan.max_height IS '计划最高高度，单位：米';
COMMENT ON COLUMN public.bo_airspace_plan.buffer_height IS '计划缓冲高度，单位：米';
COMMENT ON COLUMN public.bo_airspace_plan.plan_status IS '计划状态：1=可用，0=不可用';
COMMENT ON COLUMN public.bo_airspace_plan.remark IS '计划备注';
COMMENT ON COLUMN public.bo_airspace_plan.create_time IS '计划创建时间';
COMMENT ON COLUMN public.bo_airspace_plan.create_user IS '计划创建者';
COMMENT ON COLUMN public.bo_airspace_plan.update_time IS '计划更新时间';
COMMENT ON COLUMN public.bo_airspace_plan.update_user IS '计划更新者';
COMMENT ON COLUMN public.bo_airspace_plan.del_flag IS '计划是否删除：t删除；f未删除';

CREATE TABLE public.bo_airspace_plan_default
    PARTITION OF public.bo_airspace_plan
    DEFAULT;

CREATE INDEX idx_bo_airspace_plan_block
    ON public.bo_airspace_plan (block_id, use_date);

CREATE INDEX idx_bo_airspace_plan_status
    ON public.bo_airspace_plan (plan_status, use_date, del_flag);

-- =============================================================================
-- 用空计划分区函数
-- =============================================================================
SELECT gis_drop_function('gis_airspace_plan_part');

CREATE OR REPLACE FUNCTION public.gis_airspace_plan_part(
    p_start_date date DEFAULT current_date,
    p_days integer DEFAULT 32
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_day_start date;
    v_day_end date;
    v_partition_name text;
    i integer;
BEGIN
    IF p_days IS NULL OR p_days <= 0 THEN
        RAISE EXCEPTION 'p_days must be greater than 0';
    END IF;

    FOR i IN 0..(p_days - 1) LOOP
        v_day_start := (p_start_date + i)::date;
        v_day_end := (v_day_start + 1)::date;
        v_partition_name := format('bo_airspace_plan_%s', to_char(v_day_start, 'YYYY_MM_DD'));

        IF to_regclass(format('public.%I', v_partition_name)) IS NULL THEN
            EXECUTE format(
                'CREATE TABLE public.%I PARTITION OF public.bo_airspace_plan FOR VALUES FROM (%L) TO (%L)',
                v_partition_name,
                v_day_start,
                v_day_end
            );
        END IF;
    END LOOP;
END;
$$;

COMMENT ON FUNCTION public.gis_airspace_plan_part(date, integer)
IS '按日自动创建用空计划分区表';

-- =============================================================================
-- 用空计划同步电子围栏
-- 说明：
--   1. bo_airspace_plan 是用空计划业务表，不直接参与飞行审核。
--   2. 飞行审核使用 bo_electric_fence，因此将有效用空计划同步为电子围栏管控区。
--   3. 同步到 bo_electric_fence 的数据统一使用 fence_type='2'，表示管控区。
--   4. 同步记录的 id 规则为：airspace_plan_{plan_id}_{YYYYMMDD}，避免和人工电子围栏混淆。
--   5. bo_airspace_block/bo_airspace_plan 不保存 use_enabled/plan_enabled。
--      bo_electric_fence.use_enabled 不由本同步函数维护。
-- 字段同步说明：
--   1. 同步字段：
--      bo_electric_fence.id            <- airspace_plan_{plan_id}_{YYYYMMDD}
--      bo_electric_fence.create_time   <- now()
--      bo_electric_fence.create_user   <- 'airspace_plan'
--      bo_electric_fence.del_flag      <- false
--      bo_electric_fence.remark        <- bo_airspace_plan.remark
--      bo_electric_fence.update_time   <- now()
--      bo_electric_fence.update_user   <- 'airspace_plan'
--      bo_electric_fence.code          <- 优先 bo_airspace_plan.plan_outid，否则 bo_airspace_block.airspace_code
--      bo_electric_fence.status        <- bo_airspace_plan.plan_status
--      bo_electric_fence.name          <- bo_airspace_block.airspace_name
--      bo_electric_fence.area          <- bo_airspace_block.airspace_area
--      bo_electric_fence.start_time    <- bo_airspace_plan.time_plan 中最早 startTime
--      bo_electric_fence.end_time      <- bo_airspace_plan.time_plan 中最晚 endTime
--      bo_electric_fence.height        <- bo_airspace_plan.max_height + bo_airspace_plan.buffer_height
--      bo_electric_fence.geom          <- bo_airspace_block.geom
--      bo_electric_fence.time_plan     <- bo_airspace_plan.time_plan
--      bo_electric_fence.use_enabled   <- 不同步，由电子围栏业务自行维护
--      bo_airspace_plan.buffer_height  <- 计划缓冲高度，仅保存在用空计划表；
--                                         bo_electric_fence 当前没有对应字段，因此不同步
--   2. 固定值字段：
--      bo_electric_fence.project_id    <- NULL
--      bo_electric_fence.type          <- '1'
--      bo_electric_fence.frequency     <- '1'
--      bo_electric_fence.week          <- NULL
--      bo_electric_fence.day           <- NULL
--      bo_electric_fence.draw_method   <- 'airspace_plan'
--      bo_electric_fence.fence_type    <- '2'，表示管控区
--   3. 未同步字段：
--      bo_airspace_block.unit_id、unit_name、airspace_type、airspace_state、
--      sync_time、create_time、create_user、update_time、update_user、del_flag；
--      bo_airspace_plan.min_height、bo_airspace_plan.buffer_height、
--      bo_airspace_plan.use_date、bo_airspace_plan.block_id 以及计划审计字段
-- =============================================================================
CREATE UNIQUE INDEX IF NOT EXISTS uk_bo_electric_fence_id
    ON public.bo_electric_fence (id);

SELECT gis_drop_function('gis_airspace_plan_fence');

CREATE OR REPLACE FUNCTION public.gis_airspace_plan_fence(
    p_start_date date DEFAULT current_date,
    p_days integer DEFAULT 32
)
RETURNS TABLE (
    update_count integer,
    insert_count integer,
    disable_count integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_end_date date;
BEGIN
    IF p_days IS NULL OR p_days <= 0 THEN
        RAISE EXCEPTION 'p_days must be greater than 0';
    END IF;

    v_end_date := (p_start_date + p_days)::date;

    WITH src AS (
        SELECT
            format('airspace_plan_%s_%s', p.plan_id, to_char(p.use_date, 'YYYYMMDD')) AS fence_id,
            b.airspace_code,
            b.airspace_name,
            b.airspace_area,
            COALESCE(p.max_height, 0) + COALESCE(p.buffer_height, 0) AS fence_height,
            b.geom,
            p.plan_outid,
            p.use_date,
            p.time_plan,
            p.plan_status,
            p.remark,
            time_range.plan_start_time,
            time_range.plan_end_time
        FROM public.bo_airspace_plan p
        JOIN public.bo_airspace_block b ON b.id = p.block_id
        LEFT JOIN LATERAL (
            SELECT
                MIN(NULLIF(item->>'startTime', '')) AS plan_start_time,
                MAX(NULLIF(item->>'endTime', '')) AS plan_end_time
            FROM jsonb_array_elements(
                CASE
                    WHEN btrim(COALESCE(p.time_plan, '')) ~ '^\s*\['
                    THEN p.time_plan::jsonb
                    ELSE '[]'::jsonb
                END
            ) AS items(item)
        ) AS time_range ON true
        WHERE p.use_date >= p_start_date
          AND p.use_date < v_end_date
          AND p.del_flag = false
          AND b.del_flag = false
          AND b.geom IS NOT NULL
    ),
    upd AS (
        UPDATE public.bo_electric_fence f
        SET
            update_time = now(),
            update_user = 'airspace_plan',
            del_flag = false,
            remark = src.remark,
            code = COALESCE(src.plan_outid, src.airspace_code),
            status = src.plan_status,
            name = src.airspace_name,
            type = '1',
            frequency = '1',
            area = src.airspace_area::varchar,
            start_time = src.plan_start_time,
            end_time = src.plan_end_time,
            draw_method = 'airspace_plan',
            height = src.fence_height,
            fence_type = '2',
            geom = src.geom,
            time_plan = src.time_plan
        FROM src
        WHERE f.id = src.fence_id
        RETURNING f.id
    ),
    ins AS (
        INSERT INTO public.bo_electric_fence (
            id,
            create_time,
            create_user,
            del_flag,
            remark,
            update_time,
            update_user,
            project_id,
            code,
            status,
            name,
            type,
            frequency,
            area,
            week,
            day,
            start_time,
            end_time,
            draw_method,
            height,
            fence_type,
            geom,
            time_plan
        )
        SELECT
            src.fence_id,
            now(),
            'airspace_plan',
            false,
            src.remark,
            now(),
            'airspace_plan',
            NULL,
            COALESCE(src.plan_outid, src.airspace_code),
            src.plan_status,
            src.airspace_name,
            '1',
            '1',
            src.airspace_area::varchar,
            NULL,
            NULL,
            src.plan_start_time,
            src.plan_end_time,
            'airspace_plan',
            src.fence_height,
            '2',
            src.geom,
            src.time_plan
        FROM src
        WHERE NOT EXISTS (
            SELECT 1
            FROM public.bo_electric_fence f
            WHERE f.id = src.fence_id
        )
        RETURNING id
    ),
    dis AS (
        UPDATE public.bo_electric_fence f
        SET
            update_time = now(),
            update_user = 'airspace_plan',
            del_flag = true
        WHERE f.id LIKE 'airspace_plan_%'
          AND f.id ~ '^airspace_plan_.*_[0-9]{8}$'
          AND f.fence_type = '2'
          AND to_date(substring(f.id FROM '([0-9]{8})$'), 'YYYYMMDD') >= p_start_date
          AND to_date(substring(f.id FROM '([0-9]{8})$'), 'YYYYMMDD') < v_end_date
          AND NOT EXISTS (
              SELECT 1
              FROM src
              WHERE src.fence_id = f.id
          )
        RETURNING f.id
    )
    SELECT
        (SELECT count(*)::integer FROM upd),
        (SELECT count(*)::integer FROM ins),
        (SELECT count(*)::integer FROM dis)
    INTO update_count, insert_count, disable_count;

    RETURN NEXT;
END;
$$;

COMMENT ON FUNCTION public.gis_airspace_plan_fence(date, integer)
IS '将用空计划同步到电子围栏表，作为管控区参与飞行审核';

-- =============================================================================
-- 调用示例
-- =============================================================================
-- SELECT public.gis_airspace_plan_part(current_date, 32);
-- SELECT public.gis_airspace_plan_part(DATE '2026-09-24', 32);
-- SELECT * FROM public.gis_airspace_plan_fence(current_date, 2);

-- 新库初始化：创建今天和明天的用空计划分区。
SELECT public.gis_airspace_plan_part(current_date, 2);

-- =============================================================================
-- 三、模拟空域区块函数
-- =============================================================================
SELECT gis_drop_function('gis_airspace_block_demo');

CREATE OR REPLACE FUNCTION public.gis_airspace_block_demo(
    p_count integer DEFAULT 100
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    v_count integer;
BEGIN
    IF p_count IS NULL OR p_count <= 0 THEN
        RAISE EXCEPTION 'p_count must be greater than 0';
    END IF;

    INSERT INTO public.bo_airspace_block (
        outid,
        unit_id,
        unit_name,
        airspace_code,
        airspace_name,
        airspace_type,
        airspace_area,
        airspace_state,
        fence_type,
        remark,
        sync_time,
        create_time,
        create_user,
        update_time,
        update_user,
        del_flag,
        geom
    )
    SELECT
        format('demo-block-%s', lpad(seq::text, 6, '0')),
        format('demo-unit-%s', ((seq - 1) % 10 + 1)),
        format('模拟用空单位%s', ((seq - 1) % 10 + 1)),
        format('DEMO-AS-%s', lpad(seq::text, 6, '0')),
        format('模拟空域区块%s', lpad(seq::text, 6, '0')),
        CASE seq % 3
            WHEN 0 THEN 'REPORT'
            WHEN 1 THEN 'CONTROL'
            ELSE 'MONITOR'
        END,
        round((0.018 + (seq % 7) * 0.006)::numeric, 3)::double precision,
        CASE seq % 3
            WHEN 0 THEN 'MONITOR'
            WHEN 1 THEN 'CONTROL'
            ELSE 'REPORT'
        END,
        '2',
        '模拟数据：空域区块',
        now(),
        now(),
        'demo',
        now(),
        'demo',
        false,
        ST_MakeEnvelope(
            115.925 + (((seq - 1) % 20) * 0.0030),
            36.410 + (((seq - 1) / 20) * 0.0025),
            115.925 + (((seq - 1) % 20) * 0.0030) + 0.0018 + ((seq % 5) * 0.00015),
            36.410 + (((seq - 1) / 20) * 0.0025) + 0.0015 + ((seq % 4) * 0.00015),
            4326
        )
    FROM generate_series(1, p_count) AS s(seq)
    ON CONFLICT (outid) DO UPDATE SET
        unit_id = EXCLUDED.unit_id,
        unit_name = EXCLUDED.unit_name,
        airspace_code = EXCLUDED.airspace_code,
        airspace_name = EXCLUDED.airspace_name,
        airspace_type = EXCLUDED.airspace_type,
        airspace_area = EXCLUDED.airspace_area,
        airspace_state = EXCLUDED.airspace_state,
        fence_type = EXCLUDED.fence_type,
        remark = EXCLUDED.remark,
        sync_time = EXCLUDED.sync_time,
        update_time = now(),
        update_user = 'demo',
        del_flag = false,
        geom = EXCLUDED.geom;

    SELECT count(*)::integer
    INTO v_count
    FROM public.bo_airspace_block
    WHERE outid LIKE 'demo-block-%';

    RETURN v_count;
END;
$$;

COMMENT ON FUNCTION public.gis_airspace_block_demo(integer)
IS '生成或更新模拟空域区块数据';

-- =============================================================================
-- 四、模拟用空计划函数
-- =============================================================================
SELECT gis_drop_function('gis_airspace_plan_demo');

CREATE OR REPLACE FUNCTION public.gis_airspace_plan_demo(
    p_plans_per_block integer DEFAULT 3,
    p_days integer DEFAULT 2
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    v_count integer;
BEGIN
    IF p_plans_per_block IS NULL OR p_plans_per_block <= 0 THEN
        RAISE EXCEPTION 'p_plans_per_block must be greater than 0';
    END IF;

    IF p_days IS NULL OR p_days <= 0 THEN
        RAISE EXCEPTION 'p_days must be greater than 0';
    END IF;

    PERFORM public.gis_airspace_plan_part(current_date, p_days);

    INSERT INTO public.bo_airspace_plan (
        block_id,
        plan_outid,
        use_date,
        time_plan,
        min_height,
        max_height,
        buffer_height,
        plan_status,
        remark,
        create_time,
        create_user,
        update_time,
        update_user,
        del_flag
    )
    SELECT
        b.id,
        format('demo-plan-%s-%s', b.outid, plan_seq),
        current_date + (((block_seq + plan_seq - 2) % p_days)::integer),
        jsonb_build_array(
            jsonb_build_object(
                'startTime', to_char(((8 + plan_seq * 2)::text || ':00:00')::time, 'HH24:MI:SS'),
                'endTime', to_char(((10 + plan_seq * 2)::text || ':00:00')::time, 'HH24:MI:SS')
            )
        )::text,
        CASE WHEN plan_seq % 4 = 0 THEN 30 ELSE 0 END::double precision,
        CASE WHEN plan_seq % 5 = 0 THEN 180 ELSE 120 END::double precision,
        20::double precision,
        '1',
        '模拟数据：一个空域区块对应多个用空计划',
        now(),
        'demo',
        now(),
        'demo',
        false
    FROM (
        SELECT
            b.*,
            row_number() OVER (ORDER BY b.id) AS block_seq
        FROM public.bo_airspace_block b
        WHERE b.outid LIKE 'demo-block-%'
          AND b.del_flag = false
    ) b
    CROSS JOIN generate_series(1, p_plans_per_block) AS p(plan_seq)
    ON CONFLICT (plan_outid, use_date) DO UPDATE SET
        block_id = EXCLUDED.block_id,
        time_plan = EXCLUDED.time_plan,
        min_height = EXCLUDED.min_height,
        max_height = EXCLUDED.max_height,
        buffer_height = EXCLUDED.buffer_height,
        plan_status = EXCLUDED.plan_status,
        remark = EXCLUDED.remark,
        update_time = now(),
        update_user = 'demo',
        del_flag = false;

    SELECT count(*)::integer
    INTO v_count
    FROM public.bo_airspace_plan
    WHERE plan_outid LIKE 'demo-plan-%';

    RETURN v_count;
END;
$$;

COMMENT ON FUNCTION public.gis_airspace_plan_demo(integer, integer)
IS '生成或更新模拟用空计划数据';

-- =============================================================================
-- 模拟数据调用示例
-- =============================================================================
-- 先生成100个模拟区块，再为每个区块生成3条今天/明天计划。
-- SELECT public.gis_airspace_block_demo(100);
-- SELECT public.gis_airspace_plan_demo(3, 2);
-- SELECT * FROM public.gis_airspace_plan_fence(current_date, 2);

-- =============================================================================
-- 五、空域区块查询接口及后台SQL
-- =============================================================================
-- 1.1 空域区块查询
-- 接口：GET /api/airspace/blocks
-- 用途：查询空域区块界面列表和地图展示数据。
--
--  查询空域前端请求参数
-- 参数：
--   airspace_code  string    否，空域编号，支持模糊查询
--   airspace_name  string    否，空域名称，支持模糊查询
--   airspace_type  string    否，空域类型字典编码
--   airspace_state string    否，默认状态字典编码
--
-- 查询规则：
--   1. 一个接口直接查询符合条件的全部未删除空域区块。
--   2. 不分页，不区分列表模式和地图模式。
--   3. 每条记录直接返回GeoJSON空间字段。
--   4. 数据量较大时，后端应结合筛选条件和数据库空间索引控制查询耗时。
--   5. airspace_type、airspace_state均为字典字段，前端传字典编码，
--      后端按编码查询；字典名称由前端或后端字典服务转换。
--
--  后端返回参数
-- 返回格式：
--   code       integer   0表示成功，非0表示失败
--   message    string    返回说明
--   data       array     空域区块集合
--
-- data数组元素字段：
--   id             bigint    区块主键
--   outid          string    第三方空域区块唯一标识
--   unit_id        string    所属单位ID
--   unit_name      string    所属单位名称
--   airspace_code  string    空域编号
--   airspace_name  string    空域名称
--   airspace_type  string    空域类型字典编码
--   airspace_state string    默认状态字典编码
--   airspace_area  number    空域面积，平方公里
--   fence_type     string    围栏类型
--   geom           object    GeoJSON Feature
--
-- 空间字段返回规则：
--   1. geom使用GeoJSON格式，坐标系为WGS84（EPSG:4326）。
--   2. 前端地图建议接收GeoJSON Geometry；如果地图组件要求Feature，
--      后端再将属性字段组装为GeoJSON Feature。
--
--   PostgreSQL语句
-- 接口：GET /api/airspace/blocks
-- 查询符合条件的全部区块数据。
SELECT
    b.id,
    b.outid,
    b.unit_id AS unit_id,
    b.unit_name AS unit_name,
    b.airspace_code AS airspace_code,
    b.airspace_name AS airspace_name,
    b.airspace_type AS airspace_type,
    b.airspace_state AS airspace_state,
    b.airspace_area,
    b.fence_type,
    json_build_object(
        'type', 'Feature',
        'properties', '{}'::json,
        'geometry', ST_AsGeoJSON(b.geom)::json
    ) AS geom,
    b.create_time,
    b.update_time
FROM public.bo_airspace_block b
WHERE b.del_flag = false
ORDER BY b.airspace_code NULLS LAST, b.id;

-- =============================================================================
-- 2.1 用空计划查询
-- =============================================================================
-- 接口：GET /api/airspace/plans
-- 用途：根据空域区块条件和使用日期查询用空计划明细。
-- 关联关系：
--   bo_airspace_plan.block_id = bo_airspace_block.id
--   一条 bo_airspace_block 记录可以关联多条 bo_airspace_plan 记录（一对多）。
--   本接口按计划明细返回，一条用空计划返回一条记录。
--   同一区块存在多条计划时，区块字段会随每条计划重复返回，这是正常结果。
--
--   查询用空计划前端请求参数
-- 参数：
--   airspace_code  string    否，空域编号，支持模糊查询
--   airspace_name  string    否，空域名称，支持模糊查询
--   airspace_type  string    否，空域类型字典编码
--   airspace_state string    否，默认状态字典编码
--   use_date       date      是，使用日期，格式：YYYY-MM-DD
--
-- 查询规则：
--   1. 以上四个空域区块查询条件关联 bo_airspace_block 使用。
--   2. use_date 关联 bo_airspace_plan.use_date 查询。
--   3. 只返回存在指定日期有效用空计划的空域区块和计划。
--   4. 本接口只返回空域区块，不返回plans计划数组。
--   5. 当前 SQL 示例日期先写死为 DATE '2026-09-28'，便于直接执行测试；
--      后端正式调用时，将 DATE '2026-09-28' 替换为 :use_date::date。
--
--   用空计划后端返回参数
-- 返回格式：
--   code       integer   0表示成功，非0表示失败
--   message    string    返回说明
--   data       array     空域区块集合
--   注意：data数组元素是一个空域区块，不包含plans计划数组。
--
-- data数组元素（区块）字段：
--   id             bigint    区块主键
--   outid          string    第三方空域区块唯一标识
--   unit_id        string    所属单位ID
--   unit_name      string    所属单位名称
--   airspace_code  string    空域编号
--   airspace_name  string    空域名称
--   airspace_type  string    空域类型字典编码
--   airspace_state string    默认状态字典编码
--   airspace_area  number    空域面积，平方公里
--   fence_type     string    围栏类型
--   geom           object    GeoJSON Feature
--
--   PostgreSQL语句
-- 查询符合条件且在指定日期存在有效用空计划的全部空域区块。
SELECT
    b.id,
    b.outid,
    b.unit_id,
    b.unit_name,
    b.airspace_code,
    b.airspace_name,
    b.airspace_type,
    b.airspace_state,
    b.airspace_area,
    b.fence_type,
    json_build_object(
        'type', 'Feature',
        'properties', '{}'::json,
        'geometry', ST_AsGeoJSON(b.geom)::json
    ) AS geom
FROM public.bo_airspace_block b
WHERE b.del_flag = false
  AND EXISTS (
      SELECT 1
      FROM public.bo_airspace_plan p
      WHERE p.block_id = b.id
        AND p.del_flag = false
        AND p.use_date = DATE '2026-09-28'
  )
 
ORDER BY b.airspace_code NULLS LAST, b.id;

-- =============================================================================
-- 2.2 根据区块ID查询用空计划
-- =============================================================================
-- 接口：GET /api/airspace/blocks/{block_id}/plans
-- 用途：根据空域区块ID和使用日期查询该区块下的用空计划数组。
--
--  查询用空计划前端请求参数
-- 参数：
--   block_id       bigint    必填，空域区块主键
--   use_date       date      必填，使用日期，格式：YYYY-MM-DD
--
--   用空计划后端返回参数
-- 返回格式：
--   code       integer   0表示成功，非0表示失败
--   message    string    返回说明
--   data       array     当前区块下的用空计划集合
--
-- data数组元素字段：
--   plan_id        bigint    用空计划主键
--   block_id       bigint    空域区块主键
--   plan_outid     string    第三方计划唯一标识
--   use_date       date      使用日期
--   time_plan      string    时间计划，仅保存时分秒
--   min_height    number     最低高度，米
--   max_height    number     最高高度，米
--   buffer_height number     缓冲高度，米
--   plan_status    string    计划状态字典编码
--   remark         string    计划备注
--
--   PostgreSQL语句
-- 当前 SQL 示例日期先写死为 DATE '2026-09-28'，后端调用时替换为 :use_date::date。
-- 后端查询结果统一封装为 data 数组；SQL 每条计划返回一行。
SELECT
    p.plan_id,
    p.block_id,
    p.plan_outid,
    p.use_date,
    p.time_plan,
    p.min_height,
    p.max_height,
    p.buffer_height,
    p.plan_status,
    p.remark
FROM public.bo_airspace_plan p
WHERE p.block_id = :block_id
  AND p.del_flag = false
  AND p.use_date = DATE '2026-09-28'
ORDER BY p.plan_id;

-- =============================================================================
-- 四、按日期和24小时时间轴查询空域区块
-- =============================================================================
-- 用途：选择某一天后，时间轴按24小时移动，查询当前时刻对应的空域区块。
-- 关联关系：
--   bo_airspace_plan.block_id = bo_airspace_block.id
--   一个空域区块可以对应多条用空计划。
--   只要区块下有一条计划在当前时间段内生效，就返回该区块。
--
-- 4.1 查询空域区块前端请求参数
-- 参数：
--   airspace_code  string    否，空域编号，支持模糊查询
--   airspace_name  string    否，空域名称，支持模糊查询
--   airspace_type  string    否，空域类型字典编码
--   airspace_state string    否，默认状态字典编码
--   use_date       date      必填，查询日期，格式：YYYY-MM-DD
--   axis_time      time      必填，24小时时间轴当前时间，格式：HH24:MI:SS
--
-- 4.2 查询结果
-- 返回符合空域区块筛选条件、指定日期、指定时间段内有效的区块。
-- 一个区块如果同时匹配多条计划，SQL按计划返回多行，后端可按block_id合并；
-- 如果前端只需要区块列表，可在后端按block_id去重。
-- 返回字段：
--   block_id       bigint    空域区块主键
--   outid          string    第三方空域区块唯一标识
--   airspace_code  string    空域编号
--   airspace_name  string    空域名称
--   airspace_type  string    空域类型字典编码
--   airspace_state string    默认状态字典编码
--   plan_id        bigint    当前生效计划主键
--   plan_outid     string    第三方计划唯一标识
--   use_date       date      使用日期
--   time_plan      string    时间计划
--   min_height     number    最低高度，米
--   max_height     number    最高高度，米
--   buffer_height  number    缓冲高度，米
--   plan_status    string    计划状态字典编码
--   geom           object    GeoJSON Feature
--
-- 4.3 PostgreSQL语句
-- 当前 SQL 示例日期和时间先写死，后端调用时替换为 :use_date::date
-- 和 :axis_time::time。
SELECT
    b.id AS block_id,
    b.outid,
    b.unit_id,
    b.unit_name,
    b.airspace_code,
    b.airspace_name,
    b.airspace_type,
    b.airspace_state,
    b.airspace_area,
    b.fence_type,
    p.plan_id,
    p.plan_outid,
    p.use_date,
    p.time_plan,
    p.min_height,
    p.max_height,
    p.buffer_height,
    p.plan_status,
    p.remark,
    json_build_object(
        'type', 'Feature',
        'properties', '{}'::json,
        'geometry', ST_AsGeoJSON(b.geom)::json
    ) AS geom
FROM public.bo_airspace_block b
JOIN public.bo_airspace_plan p
    ON p.block_id = b.id
WHERE b.del_flag = false
  AND p.del_flag = false
  AND p.plan_status = '1'
  AND p.use_date = DATE '2026-09-28'
  AND EXISTS (
      SELECT 1
      FROM jsonb_array_elements(
          CASE
              WHEN btrim(COALESCE(p.time_plan, '')) ~ '^\s*\['
              THEN p.time_plan::jsonb
              ELSE '[]'::jsonb
          END
      ) AS time_item(item)
      WHERE
          (
              :axis_time::time >= (time_item.item->>'startTime')::time
              AND :axis_time::time < (time_item.item->>'endTime')::time
          )
          OR (
              (time_item.item->>'startTime')::time >
                  (time_item.item->>'endTime')::time
              AND (
                  :axis_time::time >= (time_item.item->>'startTime')::time
                  OR :axis_time::time < (time_item.item->>'endTime')::time
              )
          )
  )
  AND (
      NULLIF(btrim(:airspace_code), '') IS NULL
      OR b.airspace_code ILIKE '%' || btrim(:airspace_code) || '%'
  )
  AND (
      NULLIF(btrim(:airspace_name), '') IS NULL
      OR b.airspace_name ILIKE '%' || btrim(:airspace_name) || '%'
  )
  AND (
      NULLIF(btrim(:airspace_type), '') IS NULL
      OR b.airspace_type = btrim(:airspace_type)
  )
  AND (
      NULLIF(btrim(:airspace_state), '') IS NULL
      OR b.airspace_state = btrim(:airspace_state)
  )
ORDER BY b.airspace_code NULLS LAST, b.id, p.plan_id;
