-- =============================================================================
-- 2.空域区块.sql
-- 表名称：public.bo_airspace_block
-- 表说明：空域区块信息表
-- 依赖说明：PostGIS 空间扩展。
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS postgis;

DROP TABLE IF EXISTS public.bo_airspace_block;

CREATE TABLE public.bo_airspace_block (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outid varchar(255) NOT NULL,
    airspace_code varchar(255),
    airspace_name varchar(255),
    airspace_type varchar(255),
    airspace_area double precision,
    airspace_state varchar(255),
    min_height double precision,
    max_height double precision,
    use_date varchar(32),
    time_plan varchar(4000),
    status varchar(255),
    use_enabled boolean NOT NULL DEFAULT true,
    fence_type varchar(20),
    remark varchar(1000),
    create_time timestamp(6) without time zone NOT NULL,
    create_user varchar(32),
    update_time timestamp(6) without time zone NOT NULL,
    update_user varchar(32),
    del_flag boolean NOT NULL DEFAULT false,
    geom geometry(Geometry, 4326),
    CONSTRAINT pk_bo_airspace_block PRIMARY KEY (id)
);

COMMENT ON TABLE public.bo_airspace_block IS '空域区块信息表';

COMMENT ON COLUMN public.bo_airspace_block.id IS '主键';
COMMENT ON COLUMN public.bo_airspace_block.outid IS 'OutId';
COMMENT ON COLUMN public.bo_airspace_block.airspace_code IS '空域编号';
COMMENT ON COLUMN public.bo_airspace_block.airspace_name IS '空域名称';
COMMENT ON COLUMN public.bo_airspace_block.airspace_type IS '空域类型（B类、D类）';
COMMENT ON COLUMN public.bo_airspace_block.airspace_area IS '空域面积，单位：平方公里';
COMMENT ON COLUMN public.bo_airspace_block.airspace_state IS '空域状态（管制 监视）';
COMMENT ON COLUMN public.bo_airspace_block.min_height IS '生效最低高度，单位：米';
COMMENT ON COLUMN public.bo_airspace_block.max_height IS '生效最高高度，单位：米';
COMMENT ON COLUMN public.bo_airspace_block.use_date IS '使用日期';
COMMENT ON COLUMN public.bo_airspace_block.time_plan IS '时间计划，第三方原始多段时间数据';
COMMENT ON COLUMN public.bo_airspace_block.status IS '数据状态：1=可用，0=不可用';
COMMENT ON COLUMN public.bo_airspace_block.use_enabled IS '当前时间是否可用';
COMMENT ON COLUMN public.bo_airspace_block.fence_type IS '围栏类型：1=禁飞区，2=管控区，3=试飞区/适飞区';
COMMENT ON COLUMN public.bo_airspace_block.remark IS '备注';
COMMENT ON COLUMN public.bo_airspace_block.create_time IS '创建时间';
COMMENT ON COLUMN public.bo_airspace_block.create_user IS '创建者';
COMMENT ON COLUMN public.bo_airspace_block.update_time IS '更新时间';
COMMENT ON COLUMN public.bo_airspace_block.update_user IS '更新者';
COMMENT ON COLUMN public.bo_airspace_block.del_flag IS '是否删除：t删除；f未删除';
COMMENT ON COLUMN public.bo_airspace_block.geom IS '空域范围，WGS84坐标系';

CREATE INDEX idx_bo_airspace_block_geom
    ON public.bo_airspace_block
    USING gist (geom);

-- =============================================================================
-- 示例数据：2026-09-24 到 2026-10-25，聊城市区空域区块 1000 条。
-- 坐标说明：WGS84，经纬度范围位于聊城市区附近。
-- =============================================================================
INSERT INTO public.bo_airspace_block (
    outid,
    airspace_code,
    airspace_name,
    airspace_type,
    airspace_area,
    airspace_state,
    min_height,
    max_height,
    use_date,
    time_plan,
    status,
    use_enabled,
    fence_type,
    remark,
    create_time,
    create_user,
    update_time,
    update_user,
    del_flag,
    geom
)
WITH demo_data AS (
    SELECT
        gs AS seq,
        (DATE '2026-09-24' + ((gs - 1) % 32))::date AS plan_date,
        115.925 + (((gs - 1) % 40) * 0.0020) AS min_lon,
        36.410 + (((gs - 1) / 40) * 0.0018) AS min_lat,
        0.0012 + ((gs % 5) * 0.00015) AS lon_size,
        0.0010 + ((gs % 4) * 0.00015) AS lat_size
    FROM generate_series(1, 1000) AS gs
)
SELECT
    format('third-lc-%s', lpad(seq::text, 4, '0')) AS outid,
    format('LC-AS-%s', lpad(seq::text, 4, '0')) AS airspace_code,
    format('聊城市区空域区块%s', lpad(seq::text, 4, '0')) AS airspace_name,
    CASE WHEN seq % 2 = 0 THEN 'B类' ELSE 'D类' END AS airspace_type,
    round((0.018 + (seq % 7) * 0.006)::numeric, 3)::double precision AS airspace_area,
    CASE WHEN seq % 3 = 0 THEN '监视' ELSE '管制' END AS airspace_state,
    CASE WHEN seq % 4 = 0 THEN 30 ELSE 0 END::double precision AS min_height,
    CASE WHEN seq % 5 = 0 THEN 180 ELSE 120 END::double precision AS max_height,
    to_char(plan_date, 'YYYY-MM-DD') AS use_date,
    jsonb_build_array(
        jsonb_build_object(
            'startTime', to_char(plan_date, 'YYYY-MM-DD'),
            'endTime', to_char(plan_date, 'YYYY-MM-DD')
        ),
        jsonb_build_object(
            'startTime', to_char(plan_date, 'YYYY-MM-DD'),
            'endTime', to_char(plan_date, 'YYYY-MM-DD')
        )
    )::text AS time_plan,
    '1' AS status,
    true AS use_enabled,
    ((seq - 1) % 3 + 1)::text AS fence_type,
    '示例数据：聊城市区范围内批量生成空域区块' AS remark,
    now() AS create_time,
    'system' AS create_user,
    now() AS update_time,
    'system' AS update_user,
    false AS del_flag,
    ST_MakeEnvelope(min_lon, min_lat, min_lon + lon_size, min_lat + lat_size, 4326) AS geom
FROM demo_data;
